### ISSUE TITLE
Post Python 3.10 rebuilds TODO (T10247)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#139]
<div dir="rtl"><b>Joey&nbsp;Riches</b>&nbsp;(<em>&#35;joebonrichie</em>),&nbsp;2022-04-30&nbsp;11:55:27&nbsp;UTC</div><br/>

**These had to be updated to rebuild and are not properly tested**
- [x] apparmor : spotify and hello-world snaps are okay
[] libnitrokey
[] libusd

**Needs Patches/Updating**
- [x] m64py
- [x] python-setuptools-scm : reupdate to v6
- [x] python-black : reupdate
- [x] python-entrypoints : reupdate
- [x] python-importlib-metadata : reupdate
- [x] python-testpath : reupdate
- [x] qgis : python-sip woes
- [x] veusz : python-sip woes
- [x] onionshare{-cli} : tor 11.0.9 tarball has been nuked

**Needs kernel rebuilding first**
- Kernels haven't been built against 11.3.0 yet causing out of tree modules to fail to compile
- [x] openrazer
- [x] virtualbox

**Hacks**
- [x] python-tomli : pip hack due to no toml in stdlib, build normally again
- [x] python-installer : pip hack due to no toml in stdlib, build normally again 

**Disabled Test Suite**
- Most are disabled due to circular dependencies can be reenabled once rebuilt.
- [x] python-six
- [x] python-wheel
- [x] python-attrs
- [x] python-setuptools-git
- [x] python-setuptools-scm
- [x] python-pluggy
- [x] python-pytest
- [x] python-pytest-asyncio
- [x] python-pytest-flake8
- [x] python-pytest-httpserver
- [x] python-pytest-isort
- [x] python-pytest-mock
- [x] python-pytest-relaxed : many errors
- [x] python-pytest-timeout
- [x] python-platformdirs
[] python-nose : py3 failures
- [x] python-freezegun : one failure
- [x] python-flaky
- [x] python-soupsieve
- [x] python-webencodings
[] python-cepa : https://github.com/torproject/stem/commit/36bcb170ba9097885902513640075eac2e6ce384 (needs rebasing)
- [x] python-configargparse : failures. But no failures with v.1.5.3
- [x] python-incremental
- [x] python-docopt : failure
- [x] python-helpdev
- [x] python-invoke : Direct construction of SpecModule has been deprecated, please use SpecModule.from_parent.
- [x] python-parso : failures in test/test_python_errors.py
[] python-eventlet : one failure
- [x] python-jinja : one failure
- [x] python-lsp-jsonrpc
- [x] python-lsp-server : one failure
- [x] python-m2r : failure
- [x] python-trio 
- [x] python-numpydoc
[] python-pycurl
- [x] python-pymongo
- [x] python-pyrsistent
- [x] python-rope : 6 failures
- [x] python-alembic : 1 failure (Deprecated)
[] python-stevedore
[] python-tornado
- [X] python-tox
- [x] python-jupyter_core
- [x] python-nbformat
- [x] python3-ipython
- [x] python-ipykernel
- [x] python-jupyter_client
- [x] pycangjie
- [x] python-backports.entry_points_selectable
- [x] flask
[] gst-python
- [x] xkcdpass
- [x] python-cookiecutter
- [x] pylint
- [x] python-asttokens
- [x] python-rebulk
- [x] python-seaborn

**Doesn't rebuild against python 3.10**
- [x] kdev-python : (deprecated) Will probably need to be deprecated until https://invent.kde.org/kdevelop/kdev-python/-/merge_requests/16 is ready.
- [x] ibus-cangjie: Configure, fail to detect cangjie python module

**Not yet rebuilt**
- [x] graph-tool
- [x] kdev-python (deprecated)

**Issues**
- [x] https://github.com/pypa/pip/issues/5599
     pip3 fails with ModuleNotFoundError: No module named 'pip._internal.cli.main' or pip3 launches pip(2)
     workaround is python3 -m pip
     issue came from unclean distutils to sysconfig transition in pip 22.x.x
- pre-prepared configure scripts sometimes misdetect python as v3.1, use reconfigure macro to resolve.

- Any others?

**Comment by ermo** [comment]
We're on python3.11 now, so closing this.
