### ISSUE TITLE
OpenJDK 17 Todo (T10227)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#146]
<div dir="rtl"><b>Reilly&nbsp;Brogan</b>&nbsp;(<em>&#35;ReillyBrogan</em>),&nbsp;2022-04-07&nbsp;21:25:11&nbsp;UTC</div><br/>

OpenJDK 17 is the newest Java LTS and represents a significant number of improvements over the previous OpenJDK 11 LTS.

Todo:

- [x] Bootstrap OpenJDK 17
- [x] De-Bootsrap OpenJDK 17 (Probably going to wait for 17.0.3 for this - Roughly April 19th)
- [x] Package jtreg and use it to run tests to ensure that our OpenJDK 17 build is conformant

Go through and update application package manifests to use OpenJDK 17(where supported). Where NOT supported ensure that OpenJDK 11 is an explicit build and rundep with appropriate environmental variables:

- [x] Arduino https://github.com/getsolus/packages/issues/7547
- [x] Bisq https://github.com/getsolus/packages/issues/7542 1.x branch needs JDK 11, future 2.x should support JDK 21
- [x] Chatty
- [x] Cryptomator
- [x] Davmail
- [x] DBeaver
- [x] Fop
- [x] Freeplane
- [x] jabref
- [x] josm (on JDK 21)
- [x] ipscan
- [x] Languagetool
- [x] Modelio (deprecated)
- [x] PDFSam
- [x] ProjectLibre ~~(has UI issues running under JDK 17, keep at 11 for now - https://sourceforge.net/p/projectlibre/tickets/174/)~~ https://github.com/getsolus/packages/pull/7549

Update build tools and their dependencies to use OpenJDK 17 by default:

- [x] closure-compiler (on JDK 21)
- [x] emscripten https://github.com/getsolus/packages/pull/7544
- [x] apache-maven
- [x] scala https://github.com/getsolus/packages/pull/7545
- [x] sbt (on JDK 21)
- [x] gradle
- [x] bazel (on OpenJDK 21)
- [x] apache-ant ( on JDK 21)
- [x] clojure-tools (on JDK 17)
- [x] kotlin https://github.com/getsolus/packages/issues/7561

Stragglers on JDK 11

- [x] bisq 1.x branch needs JDK 11, future 2.x should support JDK 21
- [x] jtreg https://github.com/getsolus/packages/pull/9194

**Comment by androidnisse** [comment]
* closure-compiler has been updated and uses openjdk-21 now.

**Comment by liontiger23** [comment]
Bisq is now able to build with openjdk-21

https://github.com/getsolus/packages/pull/9172

**Comment by androidnisse** [comment]
We can drop openjdk-11 after these two merge, everything is on 17/21 now.
https://github.com/getsolus/packages/pull/9171
https://github.com/getsolus/packages/pull/9194
