### ISSUE TITLE
META: fprintd integration improvements (T7929)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#189]
<div dir="rtl"><b>Jacob</b>&nbsp;(<em>&#35;Jacalz</em>),&nbsp;2019-05-04&nbsp;19:52:23&nbsp;UTC</div><br/>

This is a META task for improving the whole integration of `fprintd` on Solus and especiall when using fingerprint readers on the Gnome desktop. Fedora currently has wonderful support for fingerprint scanners and I hope that these could be integrated in to Solus. Below are point of interest that should be improved up on in order to get a great experience:

- [ ] Enable sudo unlock using fingerprint. This falls back to password if user takes too long time.
- [ ] Force the use of password in order to modify fingerprints (not done on Fedora, but suggested on ArchWiki)
- [ ] Add documentation for `fprintd` on the help-center-docs (I will see about this myself when we have better integration)

Gnome specifics:

- [x] Allow unlocking of `gdm` using fingerprint  (see D8542)
- [ ] Get the fingerprint support wired in to gnome-control-center
- [x] Unlocking gnome-screensaver using fingerprint (see D8542)

##Image examples of some improvements:
{F4686930}
{F4686932}
{F4686935}

A good starting point for the integration points would be to have a look at spec files from [Fedora](https://apps.fedoraproject.org/packages/).

**Comment by TraceyC77** [comment]
@ermo , given the age of this issue, I suggest breaking out the outstanding issues into separate github issues and making a sub-goal or whatever GitHub allows.
Individual issues will mean work can happen on the various parts without becoming lost

**Comment by sheepman4267** [comment]
For security reasons, we're not enabling polkit/sudo via fingerprint out of the box. 

Meanwhile, in the intervening 6 years since this issue was filed, all the major DEs we ship have implemented session unlock support using fprintd, and GUI methods of enrolling/unenrolling fingerprints are widely available. 

So... this is done!

Yay!
