### ISSUE TITLE
Meta: GNOME 43 Unresolved Issues (T10401)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#232]
<div dir="rtl"><b>Evan&nbsp;Maddock</b>&nbsp;(<em>&#35;EbonJaeger</em>),&nbsp;2022-09-26&nbsp;21:36:01&nbsp;UTC</div><br/>

GNOME 43 has arrived! With it has come a few problems that still need to be addressed. This task will be updated as items are found or addressed. Feedback and notices of package breakages as a result of this stack upgrade are welcome and encouraged!

# Current Status

Synced to Stable as of October 14.

# Known Issues
- [x] `gnome-terminal`: Nautilus 43 has a new extension API, but gnome-terminal has not yet seen a release. This means that there is no "Open in Terminal" option for directories, and gnome-terminal cannot actually be rebuilt. Fedora 37 is using an unreleased version of gnome-terminal with [this patch](https://src.fedoraproject.org/rpms/gnome-terminal/blob/rawhide/f/gnome-terminal-3.45.90-nautilus-extension.patch), which does restore the functionality.
- [x] `libwnck`: [New behavior can cause calling code to break](https://gitlab.gnome.org/GNOME/libwnck/-/issues/155). Affected packages:
  - bamf
    - plank
    - vala-panel-appmenu
- [ ] `xdg-desktop-portal-gtk`: Trying to set a wallpaper from a file in Nautilus resets the wallpaper back to default. The xdg-desktop-portal wallpaper portal appears as expected, but then wallpaper is reset on clicking Apply. So far I have been unsuccessful in getting any kind of debugging messages to give a direction.
- [x] `nextcloud-client`: After the recent update on 10/14 the integration of Nextcloud in Nautilus is partially broken. [See here](https://github.com/nextcloud/desktop/issues/5041). A patch to fix this has [been merged upstream](https://github.com/nextcloud/desktop/pull/5105).
- [x] `rhythmbox`: libsoup version mismatch causes it to segfault on open. Rhythmbox uses libsoup 2, but grilo (a dependency of Rhythmbox) uses libsoup 3. [See here](https://discuss.getsol.us/d/8882-rhythmbox-not-starting-for-anyone-else).

**Comment by davidjharder** [comment]
Nautilus wallpaper reset issue still exists, nemo works as exoected

**Comment by ermo** [comment]
@davidjharder Is this still an issue since GNOME 44 landed?

**Comment by rav101** [comment]
I'll currently on Gnome, I will check in the next couple of days but I'm pretty sure I set a wallpaper from default nautilus and it worked perfectly last week over the Christmas break.

**Comment by rav101** [comment]
Just to confirm, I have set a few wallpapers on Gnome 45, and it applies correctly and doesn't reset back to default at any point. Hope this helps.
