### ISSUE TITLE
Solus 4.5 ISO checklist (T10476)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#305]
<div dir="rtl"><b>Thomas&nbsp;Staudinger</b>&nbsp;(<em>@Staudey</em>),&nbsp;2023-04-20&nbsp;19:04:54&nbsp;UTC</div><br/>

# Solus 4.5 ISO checklist

The bigger feature release after 4.4

##### General

- [x] Blogpost: Solus 4.5 release (@EbonJaeger and @davidjharder)
- [x] Fresh solbuild image (@TraceyC77 and @HarveyDevel)
- [x] Refresh appstream data for solus-sc (@joebonrichie and @TraceyC77)
  see https://github.com/getsolus/solus-appstream-data/issues/2 
- [x] Up to date desktop collage image of installed environment for all DEs
- [x] OpenCL: Verify basic ROCm 5.5 support is working (@GZGavinZhao and @ermo)
  see #701
- [x] OpenCL: Verify basic intel-compute-runtime support is working (@ermo, @joebonrichie, @EbonJaeger)
- [x] GNU Toolchain upgrade (@joebonrichie)
- [x] Implement #157 due to new glibc dropping support for legacy HWCaps (@joebonrichie) 
- [x] Ensure that baselayout is up to date (iana-protocols is 10 years out of date for instance -- [use this repo going forward](https://github.com/Mic92/iana-etc)) (@ermo)
- [x] Update Samba to newest maintenance release (4.17.x as of this writing) (@ermo)
- [x] Land working Xfce stack. (Landed and verifed working since https://github.com/getsolus/packages/commit/71d66598a3a4791305204cccd07fb265737943b7) (@ZachBacon)
- [x] Switch branding defaults to Noto Sans + Noto Serif (@sheepman4267 and @joebonrichie)
  currently, the serif font defaults to Clear Sans
  (should be a serif font -- see #208)
- [x] Create branding package for Xfce stack -- go/no-go deadline is 2023-11-10 (@ZachBacon and @EbonJaeger)
- [x] Switch out os-installer for calamares (@EbonJaeger, @davidjharder and @TraceyC77)
  see #338 (go/no-go deadline for 4.5 inclusion is on 2023-11-10)
  - [x] STRETCH GOAL: btrfs support for installer
  - [x] STRETCH GOAL: f2fs support for installer
  - [ ] ~~STRETCH GOAL: XFS support for installer~~ <sub>We will not do XFS support as it's an enterprise filesystem and we don't consider it well-suited for the desktop use-case (ie. Solus). In particular, if the system crashes/loses power unexpectedly and the root fs is formatted as XFS, the user might be dumped to a console during boot due to the FS insisting on being manually repaired. Ext4 is way more robust in this particular instance.</sub>  
- [x] STRETCH GOAL: Update PAM & friends (@ReillyBrogan and @ermo)
  and streamline as appropriate -- may resolve #259
- [x] STRETCH GOAL: Ensure that Yescrypt password hashes are created by ISO installer
- [x] STRETCH GOAL: wxwidgets gtk3
- [x] STRETCH GOAL: dbus-broker by default
- [x] STRETCH GOAL: pipewire by default
- [x] STRETCH GOAL: wayland session support across KDE and GNOME (Budgie 10.8.x and Xfce 4.18.x only support X11 sessions) (see also #204)
- [x] STRETCH GOAL: Nvidia: enable `nvidia-drm.modeset=1` for OOTB wayland support (needs GDM fixes)
- [x] STRETCH GOAL: Fix LDM (@sheepman4267 and @joebonrichie)
  see #163
  and #164
- [x] STRETCH GOAL: Sort out livecd gdm config vs. installed system gdm config (@sheepman4267, @EbonJaeger, @ZachBacon)
  see #209
- [ ] ~~STRETCH GOAL: flatpak support in Software Center(s) (@sheepman4267 and @joebonrichie)~~ Deferred to 4.6
  see #716
  and #718
- [x] STRETCH GOAL: full ROCm 5.5 stack and PyTorch with ROCm support OOTB
  see #197
- [ ] ~~STRETCH GOAL: Fix LSI (@ikeycode)~~ Serpent development is more important, and we have workarounds
- [ ] ~~STRETCH GOAL: Check up on brisk menu and do misc. cleanups (@EbonJaeger)~~ <sub>This has been deprecated along with the MATE edition. We're using Whisker Menu for XFCE instead.</sub>
- [ ] ~~STRETCH GOAL: Implement merged /usr for systemd (#293)~~ <sub>We have a bit of time before this must be finished. Stretch goal for 4.6, must have for 4.7.</sub>

##### DE specific

ISO testing instructions: https://help.getsol.us/docs/user/contributing/testing-an-iso

- [ ] Budgie @EbonJaeger
    - [ ] Boot: UEFI
    - [ ] Boot: BIOS
    - [ ] Boot: UEFI w/ LVM
    - [ ] Boot: UEFI w/ LVM+LUKS
    - [ ] Boot: BIOS w/ LVM
    - [ ] Boot: BIOS w/ LVM+LUKS
    - [ ] VM
        - [ ] VirtualBox
        - [ ] Virt Manager
    - [ ] SAMBA smoketest with Windows Shares and Shares created on Linux are visible on Windows/Android
    - [ ] AMD RDNA 2/3 GPUs
    - [ ] Intel Arc GPUs
    - [ ] Nvidia GPUs
        - [ ] 470
        - [ ] Current
        - [ ] Beta
    - [ ] Any other issues here
- [ ] GNOME @JoeyRiches
    - [ ] Boot: UEFI
    - [ ] Boot: BIOS
    - [ ] Boot: UEFI w/ LVM
    - [ ] Boot: UEFI w/ LVM+LUKS
    - [ ] Boot: BIOS w/ LVM
    - [ ] Boot: BIOS w/ LVM+LUKS
    - [ ] VM
        - [ ] VirtualBox
        - [ ] Virt Manager
    - [ ] SAMBA smoketest with Windows Shares and Shares created on Linux are visible on Windows/Android
    - [ ] AMD RDNA 2/3 GPUs
    - [ ] Intel Arc GPUs
    - [ ] Nvidia GPUs
        - [ ] 470
        - [ ] Current
        - [ ] Beta
    - [ ] Any other issues here
- [ ] Plasma @TraceyC77, @ReillyBrogan 
    - [ ] Boot: UEFI
    - [ ] Boot: BIOS
    - [ ] Boot: UEFI w/ LVM
    - [ ] Boot: UEFI w/ LVM+LUKS
    - [ ] Boot: BIOS w/ LVM
    - [ ] Boot: BIOS w/ LVM+LUKS
    - [ ] VM
        - [ ] VirtualBox
        - [x] Virt Manager
    - [ ] SAMBA smoketest with Windows Shares and Shares created on Linux are visible on Windows/Android
    - [ ] AMD RDNA 2/3 GPUs
    - [ ] Intel Arc GPUs
    - [ ] Nvidia GPUs
        - [ ] 470
        - [ ] Current
        - [ ] Beta
    - [ ] Any other issues here
- [ ] Xfce @ZachBacon, @TraceyC77
    - [ ] Boot: UEFI
    - [ ] Boot: BIOS
    - [ ] Boot: UEFI w/ LVM
    - [ ] Boot: UEFI w/ LVM+LUKS
    - [ ] Boot: BIOS w/ LVM
    - [ ] Boot: BIOS w/ LVM+LUKS
    - [ ] VM
        - [ ] VirtualBox
        - [ ] Virt Manager
    - [ ] SAMBA smoketest with Windows Shares and Shares created on Linux are visible on Windows/Android
    - [ ] AMD RDNA 2/3 GPUs
    - [ ] Intel Arc GPUs
    - [ ] Nvidia GPUs
        - [ ] 470
        - [ ] Current
        - [ ] Beta
    - [ ] Any other issues here

**Comment by TraceyC77** [comment]
When testing the VM clients, please make sure copy & paste works. This has been a problem a couple of times in the past.

**Comment by 10leej** [comment]
Proposal while we wait for this, 4.4.1 release thats really just packaged updates from the previous release.

**Comment by ermo** [comment]
> TraceyC (_@TraceyC77_), 2023-06-24 22:41:40 UTC
> 
> I'd like to nominate https://dev.getsol.us/T10561 to be fixed for 4.5
> 
> This was for copy and paste / clipboard not working out of the box for Virt-manager This should be tested in the ISO

https://github.com/getsolus/packages/commit/b68756cf0589e572a917048af4322dc655ea41f5 <- did that not fix it? If it didn't, I agree with you, we should focus on making sure that is fixed.

**Comment by TraceyC77** [comment]
> > TraceyC (_@TraceyC77_), 2023-06-24 22:41:40 UTC
> > I'd like to nominate https://dev.getsol.us/T10561 to be fixed for 4.5
> > This was for copy and paste / clipboard not working out of the box for Virt-manager This should be tested in the ISO
> 
> [b68756c](https://github.com/getsolus/packages/commit/b68756cf0589e572a917048af4322dc655ea41f5) <- did that not fix it? If it didn't, I agree with you, we should focus on making sure that is fixed.

That issue is closed. I recommended testing the functionality to guard against regressions in 4.5.

I plan to test it with a fresh install of the current testing ISOs and again with 4.5. I recommend anyone doing ISO testing touch this as well.

**Comment by xulongwu4** [comment]
Fixing LDM for AMD GPU + nvidia GPU on a laptop is not planned for Solus 4.5? I remember at one point it was a stretch goal for 4.4, and then moved to be a stretch goal of 4.5. Now I can't find any reference to that issue in the 4.5 task list any more. I am talking about #163 and #164.

**Comment by ermo** [comment]
> Fixing LDM for AMD GPU + nvidia GPU on a laptop is not planned for Solus 4.5? I remember at one point it was a stretch goal for 4.4, and then moved to be a stretch goal of 4.5. Now I can't find any reference to that issue in the 4.5 task list any more. I am talking about #163 and #164.

I mistakenly removed it. It's been added back now.

**Comment by ermo** [comment]
> Joshua Lee (_@10leej_), 2023-04-23 07:05:57 UTC
> 
> Any chance flathub can be enabled by default for 4.5?

Please take a look at the flatpak-related testing tasks above if you want to help us drive this forward.

**Comment by ermo** [comment]
@TraceyC77 / @davidjharder 

Do we have an "ISO testing HOWTO" in the Help Center or something? If not, maybe we should have...? If we do, we should probably link it here?

**Comment by Staudey** [comment]
There is one here: https://help.getsol.us/docs/user/contributing/testing-an-iso

**Comment by ReillyBrogan** [comment]
I marked off the PAM task and added another one to ensure that the installer creates yescrypt password hashes for users by default. This may already be happening depending on how the password is being set, we may just need to verify it. It's also not the end of the world if it doesn't happen, sha512 hashes are still considered secure.

You can test whether or not this is the case by doing the following:
```
sudo cat /etc/shadow
```
If the password hash starts with `$y$` then it's using a yescrypt hash.

**Comment by EbonJaeger** [comment]
Both Calamares and os-installer just calls out to `useradd` when creating users, so presumably nothing has to be done there as long as `useradd` is creating users with the correct password hash type. Will fire up a VM later to verify for sure.

**Comment by EbonJaeger** [comment]
Okay, so a fresh installation using a fresh build of Calamares and a fresh ISO *doesn't* encrypt hashes with yescrypt. The hash starts with `$6$`.

**Comment by EbonJaeger** [comment]
Marking off the GDM config stuff as "done" since it is safe to simply remove the livecd GDM config without replacement. We no longer modify the GDM config to disable Wayland, and the file gets created automatically later on if it is needed (if someone enables autologin, for instance).

**Comment by TraceyC77** [comment]
## 4.5 RC1
Please add your testing results for RC1 here for easy refeence.
If any issues are found, create an issue and link under the OK / Issue column
I'll make a new comment for RC2 (and any other versions)

If you're testing a smoketest ISO, please make a new comment with this type of table. Please include the filename so we know which verison of things you've tested.

## Budgie
| Tested by | Config e.g. BIOS, LVM | OK / Issue<br> details as needed |
|--------------|-----------|--------|
|              |           |        |
|              |           |        |
|              |           |        |
|              |           |        |
|              |           |        |

## Gnome
| Tested by | Config e.g. BIOS, LVM | OK / Issue<br> details as needed |
|--------------|-----------|--------|
|              |           |        |
|              |           |        |
|              |           |        |
|              |           |        |
|              |           |        |


## Plasma
| Tested by | Config e.g. BIOS, LVM | OK / Issue<br> details as needed |
|--------------|-----------|--------|
|              |           |        |
|              |           |        |
|              |           |        |
|              |           |        |
|              |           |        |


## XFCE
| Tested by | Config e.g. BIOS, LVM | OK / Issue<br> details as needed |
|--------------|-----------|--------|
|              |           |        |
|              |           |        |
|              |           |        |
|              |           |        |
|              |           |        |

**Comment by joebonrichie** [comment]
XFCE Missing polish items:
  - Super does not open whisker-menu by default OOTB to match our other editions.
  - By default whisker-menu is configured to use `mugshot` to manage user icon, this isn't installed OOTB.
  - XFCE provides no graphical user management OOTB. Either `mate-user-admin` or enable users in `gnome-system-tools` (which was last updated, 2011!), can be used. Maybe there is another alternative?
  - Autologin in livecd environment does not work

**Comment by 10leej** [comment]
> XFCE Missing polish items:
> 
>     * Super does not open whisker-menu by default OOTB to match our other editions.

This can be resolved by adding a custom keyboard shortcut calling xfce4-popup-whiskermenu. I believe the xfce settings manager can have this setup via a json config file, but I'll be honest and say I'm not privy to this since I haven't touched xfce in at least 6 years or so.

**Comment by joebonrichie** [comment]
> > XFCE Missing polish items:
> > ```
> > * Super does not open whisker-menu by default OOTB to match our other editions.
> > ```
> 
> This can be resolved by adding a custom keyboard shortcut calling xfce4-popup-whiskermenu. I believe the xfce settings manager can have this setup via a json config file, but I'll be honest and say I'm not privy to this since I haven't touched xfce in at least 6 years or so.

Thanks. We'll need to add it to https://github.com/getsolus/xfce4-desktop-branding

**Comment by joebonrichie** [comment]
- Polish: Calamares does not provide a reboot option after successful install (low priority)

**Comment by joebonrichie** [comment]
XFCE missing icon in lightdm after clicking the password field

![Screenshot from 2023-12-14 15-31-52](https://github.com/getsolus/packages/assets/5338090/3cb34f43-2dae-4599-a472-017db1c12229)

**Comment by joebonrichie** [comment]
XFCE:

`xfce4-taskmanager` is not packaged providing no system monitor OOTB

There is a missing icon for folder sharing (right click a folder and click share)


![Screenshot from 2023-12-16 16-05-43](https://github.com/getsolus/packages/assets/5338090/56edbe79-67c2-42a3-80bc-69677c7befee)

There is a theming bug with qogir in our software center

![Screenshot from 2023-12-16 15-54-50](https://github.com/getsolus/packages/assets/5338090/ab0cbf61-8a84-44c6-ac5a-f9480c8d45cc)

**Comment by joebonrichie** [comment]
BIOS: Boot loader location: Install to /boot doesn't work

**Comment by kostadinsh** [comment]
For some reason the `pipewire` package wasn't installed at all on the 2023-12-23 Plasma ISO.

**Comment by ReillyBrogan** [comment]
> For some reason the `pipewire` package wasn't installed at all when using the 2023-12-23 Plasma ISO.

Fixed, thanks!

**Comment by EbonJaeger** [comment]
Solus 4.5 Resilience Released: https://getsol.us/2024/01/08/solus-4-5-released/
