### ISSUE TITLE
Solus 4.7 Release Checklist

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#4226]
# Action Item checklist for final release

- [x] Write blog post https://github.com/getsolus/solus-site.github.io/pull/59
- ~~Bump baselayout~~ *Still broken, so no*
- [x] Update `os-release`
- [x] Sync to Shannon
- [x] Take decluttered screenshot in each desktop edition at 1080p (Installed environment with only default desktop icons after install). Create a desktop collage image and save to the [release images folder](https://github.com/getsolus/solus-site.github.io/tree/main/static/imgs/release-images) Evan was first, use images from Help center PR https://github.com/getsolus/help-center-docs/pull/596/files
- [x] Test all the things in Software Center Third Party, update where necessary
- [x] Download and import the Solus private releng GPG key from BitWarden
- [x] Cook and upload all ISOs based on stable (aka Shannon) using the ISO creation script:
  ```bash
  ./infrastructure-tooling/build_isos.sh release
  ```
  - The uploaded assets will need to be copied to the appropriate `/srv/www/downloads/isos/` folder on `packages.getsol.us`. For Release ISOs, this would be `/srv/www/downloads/isos/${VERSION}/`
  - From there it'll need to be hard linked into all backer tier folders. Use the command `ls -golthr` to see how many hardlinks an ISO has
    ```bash
    sudo mkdir /srv/www/downloads/isos/${VERSION}
    sudo ./infrastructure-tooling/make_links.sh -s ${UPLOADED_ISOS_DIR} -d ${VERSION} -t crew,beta,releasetesters
    ```
- [x] Validate all ISOs. See the GitHub task for the current release
  - [x] Budgie
  - [x] GNOME
  - [x] Plasma
  - [x] Xfce
- [x] Take de-cluttered screenshot in each edition at 1080p for use as updated release images
- [x] Update Help Center
  - [x] Update Editions
    - [x] Add/remove any editions (check paths `src/components/editions.jsx` and `docs/user/editions/` as of 4.5)
    - [x] If there are new editions, create skeletal structure for it and create issue to document configuration and tips n' tricks sections for the new edition. (check paths `docs/user/editions/` as of 4.5)
    - [x] Update edition screenshots with updated release images (check path `src/editions/$EDITION.{jpg,png}` as of 4.5)
    - [x] Ensure edition descriptions to match the descriptions on the [download](https://getsol.us/download/) page e.g. Budgie: A feature-rich, luxurious desktop using the most modern technologies. (Check paths `src/components/editions.jsx` and `i18n/en/code.json` as of 4.5.)
  - [x] Update Help Center Docs references from current release to upcoming release (e.g. 4.1 -> 4.2) https://github.com/getsolus/help-center-docs/pull/596
- ~~Sync modules via `make sync` in `solus-site`~~ This is an old step from somewhere
- [x] Update `data/info.yaml` in `solus-site` with the new version, media size, and sha256sum https://github.com/getsolus/solus-site.github.io/pull/59
- [x] Create featured image for release blog post (imagemagick collage)
- [x] Create torrent files using qBitTorrent with the following settings (if not mentioned, leave the setting at its default):
  - Torrent format: V1
  - Tracker URLS:
    `udp://tracker.opentrackr.org:1337/announce`
    `udp://tracker.openbittorrent.com:6969`
  - Web seed URLs:
    `https://downloads.getsol.us/isos/${VERSION}/Solus-${VERSION}-${EDITION}.iso`
  - Comments:
    `Solus ${VERSION} ${EDITION} Edition Official Release`
  - Example qBitTorrent GUI image:
    ![qBitTorrent example .torrent creation screenshot](/images/qbittorrent-torrent-file-creation-example.png "qBitTorrent example .torrent creation screenshot")
  - Create the .torrent file with a name template matching `Solus-${VERSION}-${EDITION}.torrent`; e.g `Solus-4.4-Budgie.torrent`
- [x] Upload .torrent files for each edition to `packages.getsol.us` and place them in `/srv/www/torrents/`
- [x] Deploy site
- [x] Deploy Help Center
- [x] Publish to social media
- [x] Party time! 🎉

Associated PRs

- https://github.com/getsolus/help-center-docs/pull/596
- https://github.com/getsolus/doflicky/pull/6
- https://github.com/getsolus/solus-site.github.io/pull/57
- https://github.com/getsolus/packages/pull/4897
- https://github.com/getsolus/packages/pull/4898

**Comment by davidjharder** [comment]
Stashing my torrent creation script here for now. 

Notes
- Requires `py3createtorrent` install with `pipx` or similar
- Assumes you are in a directory with the isos, see the globbing in INPUT, not terribly sophisticated

```
#!/bin/bash
set -E pipefail

for EDITION in "Budgie" "GNOME" "XFCE" "Plasma"
do
    VERSION="2025-01-26"
    RELEASE_TYPE="Release"
    TRACKER1="udp://tracker.opentrackr.org:1337/announce"
    WEBSEED="https://downloads.getsol.us/isos/${VERSION}/Solus-${EDITION}-${RELEASE_TYPE}-${VERSION}.iso"
    COMMENT="Solus ${EDITION} ${VERSION} Official Release"
    OUTPUT="Solus-${EDITION}-${RELEASE_TYPE}-${VERSION}"
    INPUT="*${EDITION}*"
    py3createtorrent $INPUT -t $TRACKER1 -n $OUTPUT -c "$COMMENT" --webseed $WEBSEED
done
```
