### ISSUE TITLE
Solus 4.8 Release Checklist

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#4227]
# Action Item checklist for final release

- [x] Bump `baselayout`
- [x] Update `os-release`
- [x] Check that lsb-release is up-to-date and update it if necessary
- [x] Sync to Polaris
- [x] Download and import the Solus private releng GPG key from BitWarden
- [x] Cook and upload all ISOs based on stable (aka Polaris) using the ISO creation script:
  ```bash
  ./infrastructure-tooling/build_nspawn.sh release
  ```
- [x] Upload the ISOs (the script above can do this for you)
- [x] Deploy the ISOs for download
  ```bash
  sudo ./infrastructure-tooling/deploy_isos.py <uploaded_isos_dir> --release --cleanup --tiers crew beta releasetesters
  ```
- [x] Validate all ISOs. See the GitHub task for the current release

- [x] Update Help Center
  - [x] Update Editions
    - [x] Add/remove any editions (check paths `src/components/editions.jsx` and `docs/user/editions/` as of 4.5)
    - [x] If there are new editions, create skeletal structure for it and create issue to document configuration and tips n' tricks sections for the new edition. (check paths `docs/user/editions/` as of 4.5)
    - [x] Update edition screenshots with updated release images (check path `src/editions/$EDITION.{jpg,png}` as of 4.5)
    - [x] Ensure edition descriptions to match the descriptions on the [download](https://getsol.us/download/) page e.g. Budgie: A feature-rich, luxurious desktop using the most modern technologies. (Check paths `src/components/editions.jsx` and `i18n/en/code.json` as of 4.5.)
  - [x] Update Help Center Docs references from current release to upcoming release (e.g. 4.1 -> 4.2) https://github.com/getsolus/help-center-docs/pull/343

- [x] Update website
  - [x] Take decluttered screenshot in each desktop edition at 1080p (Installed environment with only default desktop icons after install) and save to the [release images folder](https://github.com/getsolus/solus-site.github.io/tree/main/static/imgs/release-images)
  - [x] Create a desktop collage image and save to the [release images folder](https://github.com/getsolus/solus-site.github.io/tree/main/static/imgs/release-images)
  - [x] Update `data/downloads/isos.yaml` in `solus-site` with the new version, media size, and sha256sum
  - [x] Write blog post

- [x] Create torrent files using qBitTorrent with the following settings (if not mentioned, leave the setting at its default):
  - Torrent format: V1
  - Tracker URLs:
    `udp://tracker.opentrackr.org:1337/announce`
    `udp://tracker.openbittorrent.com:6969`
  - Web seed URLs:
    `https://downloads.getsol.us/isos/${VERSION}/Solus-${VERSION}-${EDITION}.iso`
  - Comments:
    `Solus ${VERSION} ${EDITION} Edition Official Release`
  - Example qBitTorrent GUI image:
    ![qBitTorrent example `.torrent` creation screenshot](/images/qbittorrent-torrent-file-creation-example.png "qBitTorrent example `.torrent` creation screenshot")
  - Create the `.torrent` file with a name template matching `Solus-${VERSION}-${EDITION}.torrent`; e.g `Solus-4.4-Budgie.torrent`
- [x] Upload `.torrent` files for each edition to `packages.getsol.us` and place them in `/srv/www/torrents/`
- [x] Deploy site
- [x] Deploy Help Center
- [x] Publish to social media
- [x] Party time! 🎉

**Comment by EbonJaeger** [comment]
Thank you everyone for their awesome work in making the epoch and this release happen! See you all for the next one.
