### ISSUE TITLE
Meta: Appstream Data Reporting Is Funky (T4875)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#6]
<div dir="rtl"><b>Joshua&nbsp;Strobl</b>&nbsp;(<em>&#35;JoshStrobl</em>),&nbsp;2017-10-26&nbsp;04:33:11&nbsp;UTC</div><br/>

This is just a meta list of all the packages that appear to have multiple appstream data's provided and thus Software Center may report them inaccurately:

Issue - Package Name - Description 

- [x] [T3720](https://phab.getsol.us/T3720) - zathura **FIXED** - zathura reports as PDF Plugin for Zathura 
- [x] [T4320](https://phab.getsol.us/T4320) - digikam **FIXED**- digikam reports as Showfoto
- [x] ~~[T4283](https://phab.getsol.us/T4283)~~ #1 - gnome-shell-extensions **FIXED** - gnome-shell-extensions reports as Workspace Indicator
- [x] ~~[T4469](https://phab.getsol.us/T4469)~~ #4 - gedit-plugins - **FIXED** gedit-plugins reports as Word completion
- [x] ~~[T5199](https://phab.getsol.us/T5199)~~ #17 - Parlatype **FIXED** - Displays as a GNOME extension.'
- [x] ~~[T5385](https://phab.getsol.us/T5385)~~ #78 - chocolate-doom  **FIXED**- Reports as Chocolate Strife
- [ ] #1364 - Calibre has wacky appstream data

**Comment by TraceyC77** [comment]
Verified that the apps not marked as fixed are still displaying incorrect information in Software Center

**Comment by ermo** [comment]
The chocolate-strife binaries and appdata is actually _part_ of the chocolate-doom release, hence it is not wrong for this to point to the same package.

If anything, the solus package should split out the chocolate-strife stuff.

```
ermo@solbox:~/repos/getsolus/monorepo/packages [main* +3 ~0 -0 !]
$ eopkg.bin info -f chocolate-doom |grep strife
/usr/bin/chocolate-strife, type: executable, size: 818584, sha1sum: e3be0238112851d38733c31f916173ae83ad6705
/usr/bin/chocolate-strife-setup, type: executable, size: 263120, sha1sum: 8f18944a282954579ba7fb128abc3965eadc694d
/usr/share/appdata/chocolate-strife.appdata.xml, type: data, size: 1807, sha1sum: 2b22ff62fe6d3bd7230e0493e0ccd620b774575f
/usr/share/applications/chocolate-strife.desktop, type: data, size: 202, sha1sum: 0673aec31d2b8382ccd00d07e7ed82b1ecb19a62
/usr/share/bash-completion/completions/chocolate-strife, type: data, size: 7299, sha1sum: c52c9a9c13cacbf26cded21cae5e38c703bc0766
/usr/share/doc/chocolate-strife/CMDLINE.strife, type: doc, size: 8917, sha1sum: 39f0c839a8e6a1f6d96c7bb122274005942a19fd
/usr/share/doc/chocolate-strife/ChangeLog, type: doc, size: 161, sha1sum: a30bec953b51af9b9734c0a2b87ec3a245638655
/usr/share/doc/chocolate-strife/INSTALL.strife, type: doc, size: 2747, sha1sum: 337bf728b2f735e7c7d4479671a0a12298c1dfcb
/usr/share/doc/chocolate-strife/NEWS.md, type: doc, size: 62317, sha1sum: 267b0fecec8c70bf9bd4a807641511b0f2372a0b
/usr/share/doc/chocolate-strife/PHILOSOPHY.md, type: doc, size: 9971, sha1sum: b667f5cc866d585b53a2e2ec34678bc45000848f
/usr/share/doc/chocolate-strife/README.Music.md, type: doc, size: 6484, sha1sum: 5813868838c40f2f75d8b9f47c31d47bf2903dc8
/usr/share/doc/chocolate-strife/README.Strife.md, type: doc, size: 5269, sha1sum: ba540abcf9b59e281aa08a47865ba78edabc9a56
/usr/share/doc/chocolate-strife/README.md, type: doc, size: 3787, sha1sum: ecb419ed5c9516650c11b0f38f192fd2b7037724
/usr/share/man/man5/chocolate-strife.cfg.5, type: man, size: 15734, sha1sum: ab431715b05f690d74d96ab84be4868033fe5cf9
/usr/share/man/man5/strife.cfg.5, type: man, size: 7033, sha1sum: 948c4c9eb66792fa7528962076f61f2a0e86cb6d
/usr/share/man/man6/chocolate-strife-setup.6, type: man, size: 1231, sha1sum: 9b5385caaa70515b763f37a2c44a012de516b703
/usr/share/man/man6/chocolate-strife.6, type: man, size: 13518, sha1sum: 855cf0034be5817b6ddc7a257e5c1d87fd6d1333
```

See also: https://www.chocolate-doom.org/wiki/index.php/Chocolate_Strife

**Comment by malfisya** [comment]
Thanks to @joebonrichie , @EbonJaeger , and @maikwoehl for helping sort this one out. Closing, cheers!🎉
